using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LoanAnnuityCalculatorAPI.Models.Debtor;
using LoanEntity = LoanAnnuityCalculatorAPI.Models.Loan.Loan;

namespace LoanAnnuityCalculatorAPI.Models
{
    /// <summary>
    /// Represents a line item in the balance sheet.
    /// This provides detailed breakdown of assets and liabilities,
    /// linking to actual loans and collateral where applicable.
    /// </summary>
    public class BalanceSheetLineItem
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey("DebtorBalanceSheet")]
        public int BalanceSheetId { get; set; }

        /// <summary>
        /// Category of the line item: CurrentAssets, FixedAssets, CurrentLiabilities, LongTermLiabilities, Equity
        /// </summary>
        [Required]
        [MaxLength(50)]
        public required string Category { get; set; }

        /// <summary>
        /// Subcategory/Label for the line item (e.g., "Cash", "Residential Real Estate", "Bank Loan #1")
        /// </summary>
        [Required]
        [MaxLength(200)]
        public required string Label { get; set; }

        /// <summary>
        /// Monetary value of this line item
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// Optional reference to a loan if this line item represents a loan liability
        /// </summary>
        [ForeignKey("Loan")]
        public int? LoanId { get; set; }

        /// <summary>
        /// Optional reference to collateral if this line item represents a collateral asset
        /// </summary>
        [ForeignKey("Collateral")]
        public int? CollateralId { get; set; }

        /// <summary>
        /// Display order for sorting line items within a category
        /// </summary>
        public int DisplayOrder { get; set; }

        /// <summary>
        /// Additional notes or description for this line item
        /// </summary>
        [MaxLength(500)]
        public string? Notes { get; set; }

        /// <summary>
        /// Whether this line item was manually entered or auto-generated from loans/collateral
        /// </summary>
        public bool IsAutoGenerated { get; set; }

        // Navigation properties
        public DebtorBalanceSheet DebtorBalanceSheet { get; set; } = null!;
        public LoanEntity? Loan { get; set; }
        public Collateral? Collateral { get; set; }
    }

    /// <summary>
    /// Constants for balance sheet categories
    /// </summary>
    public static class BalanceSheetCategory
    {
        public const string CurrentAssets = "CurrentAssets";
        public const string FixedAssets = "FixedAssets";
        public const string CurrentLiabilities = "CurrentLiabilities";
        public const string LongTermLiabilities = "LongTermLiabilities";
        public const string Equity = "Equity";
    }
}
