// <auto-generated />
using System;
using LoanAnnuityCalculatorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanAnnuityCalculatorAPI.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20251123143923_AddSectorDefinitions")]
    partial class AddSectorDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.BalanceSheetLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BalanceSheetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CollateralId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BalanceSheetId");

                    b.HasIndex("CollateralId");

                    b.HasIndex("LoanId");

                    b.ToTable("BalanceSheetLineItems");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Collateral", b =>
                {
                    b.Property<int>("CollateralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppraisalDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AppraisalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssetUniqueId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FirstMortgageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LandRegistryCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAppraisalUpdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LiquidityHaircut")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CollateralId");

                    b.HasIndex("AssetUniqueId")
                        .IsUnique()
                        .HasFilter("[AssetUniqueId] IS NOT NULL");

                    b.HasIndex("LandRegistryCode")
                        .IsUnique()
                        .HasFilter("[LandRegistryCode] IS NOT NULL");

                    b.HasIndex("PostalCode", "HouseNumber")
                        .IsUnique()
                        .HasFilter("[PostalCode] IS NOT NULL AND [HouseNumber] IS NOT NULL");

                    b.ToTable("Collaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CollateralIndex", b =>
                {
                    b.Property<int>("CollateralIndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceIndex")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CollateralIndexId");

                    b.ToTable("CollateralIndexes");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.ContractTextBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("InsertBseTable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InsertPaymentChart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RedemptionScheduleType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowSectionHeader")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContractTextBlocks");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CreditRatingSpread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Spread")
                        .HasColumnType("TEXT");

                    b.Property<int>("TariffSettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TariffSettingsId");

                    b.ToTable("CreditRatingSpreads");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FirstLienInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FirstLienLoanAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstLienRedemptionSchedule")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstLienTenorMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LongTermAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongTermLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OwnersEquity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorBalanceSheets");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", b =>
                {
                    b.Property<int>("DebtorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactCallingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactFirstNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProspect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory1Function")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory2Function")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory3Function")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory3Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DebtorID");

                    b.ToTable("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostOfGoodsSold")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EBITDA")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InterestCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestExpense")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OperatingExpenses")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxExpense")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorPLs");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorSignatory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorSignatories");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.RevenueDetail", b =>
                {
                    b.Property<int>("RevenueDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PLId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevenueCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RevenueDetailId");

                    b.HasIndex("PLId");

                    b.ToTable("RevenueDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.InvoiceSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BIC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultPaymentTerms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDateCalculation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeCompanyLogo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceNumberStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReminderDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvoiceSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.Property<int>("LoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestOnlyMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedemptionSchedule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenorMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoanID");

                    b.HasIndex("DebtorID");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LoanCollateral", b =>
                {
                    b.Property<int>("LoanCollateralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllocationPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CollateralId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoanCollateralId");

                    b.HasIndex("CollateralId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanCollaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LoanStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculationType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCalculated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoanStatuses");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LtvSpreadTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxLtv")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Spread")
                        .HasColumnType("TEXT");

                    b.Property<int>("TariffSettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TariffSettingsId");

                    b.ToTable("LtvSpreadTiers");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Payment.LoanPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapitalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysLate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaymentId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanPayments");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Ratios.CreditRatingThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RatioName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CreditRatingThresholds");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCollateralCorrelation")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCollateralExpectedReturn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCollateralVolatility")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCorporateTaxRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultEbitdaMarginVolatility")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultOperatingCostGrowthRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultOperatingCostVolatility")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultRevenueGrowthRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultRevenueVolatility")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityAgriculture")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityConstruction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityFinancialServices")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityHealthcare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityHospitality")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityManufacturing")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityOther")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityProfessionalServices")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityRealEstate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityRetail")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityTechnology")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityTransportation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.PropertyTypeParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CorrelationWithRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedReturn")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volatility")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelSettingsId");

                    b.ToTable("PropertyTypeParameters");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorCollateralCorrelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CorrelationCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelSettingsId");

                    b.ToTable("SectorCollateralCorrelations");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorCorrelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CorrelationCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sector1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelSettingsId");

                    b.ToTable("SectorCorrelations");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultVolatility")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelSettingsId");

                    b.ToTable("SectorDefinitions");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.StandardRevenueCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StandardRevenueCategories");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TariffSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TariffSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferenceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferenceValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PreferenceKey")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.BalanceSheetLineItem", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", "DebtorBalanceSheet")
                        .WithMany("LineItems")
                        .HasForeignKey("BalanceSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Collateral", "Collateral")
                        .WithMany()
                        .HasForeignKey("CollateralId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Loan.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Collateral");

                    b.Navigation("DebtorBalanceSheet");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CreditRatingSpread", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.TariffSettings", "TariffSettings")
                        .WithMany("CreditRatings")
                        .HasForeignKey("TariffSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TariffSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("BalanceSheets")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("ProfitAndLossStatements")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorSignatory", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "Debtor")
                        .WithMany("Signatories")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debtor");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.RevenueDetail", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", "DebtorPL")
                        .WithMany("RevenueDetails")
                        .HasForeignKey("PLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorPL");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("Loans")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LoanCollateral", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Collateral", "Collateral")
                        .WithMany("LoanCollaterals")
                        .HasForeignKey("CollateralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Loan.Loan", "Loan")
                        .WithMany("LoanCollaterals")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collateral");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LtvSpreadTier", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.TariffSettings", "TariffSettings")
                        .WithMany("LtvTiers")
                        .HasForeignKey("TariffSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TariffSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Payment.LoanPayment", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Loan.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.PropertyTypeParameters", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", "ModelSettings")
                        .WithMany("PropertyTypeParameters")
                        .HasForeignKey("ModelSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorCollateralCorrelation", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", "ModelSettings")
                        .WithMany("SectorCollateralCorrelations")
                        .HasForeignKey("ModelSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorCorrelation", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", "ModelSettings")
                        .WithMany("SectorCorrelations")
                        .HasForeignKey("ModelSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorDefinition", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", "ModelSettings")
                        .WithMany("SectorDefinitions")
                        .HasForeignKey("ModelSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UserPreference", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Collateral", b =>
                {
                    b.Navigation("LoanCollaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", b =>
                {
                    b.Navigation("BalanceSheets");

                    b.Navigation("Loans");

                    b.Navigation("ProfitAndLossStatements");

                    b.Navigation("Signatories");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.Navigation("RevenueDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.Navigation("LoanCollaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", b =>
                {
                    b.Navigation("PropertyTypeParameters");

                    b.Navigation("SectorCollateralCorrelations");

                    b.Navigation("SectorCorrelations");

                    b.Navigation("SectorDefinitions");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TariffSettings", b =>
                {
                    b.Navigation("CreditRatings");

                    b.Navigation("LtvTiers");
                });
#pragma warning restore 612, 618
        }
    }
}
