// <auto-generated />
using System;
using LoanAnnuityCalculatorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanAnnuityCalculatorAPI.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20251109154626_AddLiquidityHaircutToCollateral")]
    partial class AddLiquidityHaircutToCollateral
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Collateral", b =>
                {
                    b.Property<int>("CollateralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppraisalDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AppraisalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssetUniqueId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FirstMortgageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LandRegistryCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAppraisalUpdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LiquidityHaircut")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CollateralId");

                    b.HasIndex("AssetUniqueId")
                        .IsUnique()
                        .HasFilter("[AssetUniqueId] IS NOT NULL");

                    b.HasIndex("LandRegistryCode")
                        .IsUnique()
                        .HasFilter("[LandRegistryCode] IS NOT NULL");

                    b.HasIndex("PostalCode", "HouseNumber")
                        .IsUnique()
                        .HasFilter("[PostalCode] IS NOT NULL AND [HouseNumber] IS NOT NULL");

                    b.ToTable("Collaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CollateralIndex", b =>
                {
                    b.Property<int>("CollateralIndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceIndex")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CollateralIndexId");

                    b.ToTable("CollateralIndexes");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LongTermAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongTermLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OwnersEquity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorBalanceSheets");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", b =>
                {
                    b.Property<int>("DebtorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DebtorID");

                    b.ToTable("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostOfGoodsSold")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EBITDA")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InterestCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestExpense")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OperatingExpenses")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxExpense")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorPLs");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.RevenueDetail", b =>
                {
                    b.Property<int>("RevenueDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PLId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevenueCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RevenueDetailId");

                    b.HasIndex("PLId");

                    b.ToTable("RevenueDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.InvoiceSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BIC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultPaymentTerms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDateCalculation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeCompanyLogo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceNumberStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReminderDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvoiceSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.Property<int>("LoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestOnlyMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedemptionSchedule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenorMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoanID");

                    b.HasIndex("DebtorID");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LoanCollateral", b =>
                {
                    b.Property<int>("LoanCollateralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllocationPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CollateralId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoanCollateralId");

                    b.HasIndex("CollateralId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanCollaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LoanStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculationType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCalculated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoanStatuses");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Payment.LoanPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapitalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysLate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaymentId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanPayments");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Ratios.CreditRatingThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RatioName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CreditRatingThresholds");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("BalanceSheets")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("ProfitAndLossStatements")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.RevenueDetail", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", "DebtorPL")
                        .WithMany("RevenueDetails")
                        .HasForeignKey("PLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorPL");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("Loans")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LoanCollateral", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Collateral", "Collateral")
                        .WithMany("LoanCollaterals")
                        .HasForeignKey("CollateralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Loan.Loan", "Loan")
                        .WithMany("LoanCollaterals")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collateral");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Payment.LoanPayment", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Loan.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Collateral", b =>
                {
                    b.Navigation("LoanCollaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", b =>
                {
                    b.Navigation("BalanceSheets");

                    b.Navigation("Loans");

                    b.Navigation("ProfitAndLossStatements");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.Navigation("RevenueDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.Navigation("LoanCollaterals");
                });
#pragma warning restore 612, 618
        }
    }
}
