// <auto-generated />
using System;
using LoanAnnuityCalculatorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanAnnuityCalculatorAPI.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20251126111301_TieredPricingSystem")]
    partial class TieredPricingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.AddOnPermission", b =>
                {
                    b.Property<int>("AddOnPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddOnId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AddOnPermissionId");

                    b.HasIndex("AddOnId");

                    b.ToTable("AddOnPermissions");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.AddOnPricingTier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddOnId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualPricePerAssignment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyPricePerAssignment")
                        .HasColumnType("TEXT");

                    b.HasKey("TierId");

                    b.HasIndex("AddOnId");

                    b.ToTable("AddOnPricingTiers");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.BalanceSheetLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BalanceSheetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CollateralId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BalanceSheetId");

                    b.HasIndex("CollateralId");

                    b.HasIndex("LoanId");

                    b.ToTable("BalanceSheetLineItems");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Collateral", b =>
                {
                    b.Property<int>("CollateralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppraisalDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AppraisalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssetUniqueId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FirstMortgageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LandRegistryCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAppraisalUpdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LiquidityHaircut")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CollateralId");

                    b.HasIndex("AssetUniqueId")
                        .IsUnique()
                        .HasFilter("[AssetUniqueId] IS NOT NULL");

                    b.HasIndex("FundId");

                    b.HasIndex("LandRegistryCode")
                        .IsUnique()
                        .HasFilter("[LandRegistryCode] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex("PostalCode", "HouseNumber")
                        .IsUnique()
                        .HasFilter("[PostalCode] IS NOT NULL AND [HouseNumber] IS NOT NULL");

                    b.ToTable("Collaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CollateralIndex", b =>
                {
                    b.Property<int>("CollateralIndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceIndex")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CollateralIndexId");

                    b.ToTable("CollateralIndexes");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.ContractTextBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("InsertBseTable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InsertPaymentChart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RedemptionScheduleType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowSectionHeader")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContractTextBlocks");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CreditRatingSpread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Spread")
                        .HasColumnType("TEXT");

                    b.Property<int>("TariffSettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TariffSettingsId");

                    b.ToTable("CreditRatingSpreads");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FirstLienInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FirstLienLoanAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstLienRedemptionSchedule")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstLienTenorMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LongTermAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongTermLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OwnersEquity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorBalanceSheets");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", b =>
                {
                    b.Property<int>("DebtorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactCallingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactFirstNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProspect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory1Function")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory2Function")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory3Function")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signatory3Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DebtorID");

                    b.HasIndex("FundId");

                    b.HasIndex("TenantId");

                    b.ToTable("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostOfGoodsSold")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EBITDA")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InterestCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestExpense")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OperatingExpenses")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevenueSectorBreakdown")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxExpense")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorPLs");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorSignatory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorSignatories");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.RevenueDetail", b =>
                {
                    b.Property<int>("RevenueDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PLId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevenueCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RevenueDetailId");

                    b.HasIndex("PLId");

                    b.ToTable("RevenueDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Fund", b =>
                {
                    b.Property<int>("FundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FundCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FundId");

                    b.HasIndex("TenantId");

                    b.ToTable("Funds");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.InvoiceSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BIC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultPaymentTerms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDateCalculation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeCompanyLogo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceNumberStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReminderDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvoiceSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.Property<int>("LoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestOnlyMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedemptionSchedule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenorMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoanID");

                    b.HasIndex("DebtorID");

                    b.HasIndex("FundId");

                    b.HasIndex("TenantId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LoanCollateral", b =>
                {
                    b.Property<int>("LoanCollateralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllocationPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CollateralId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoanCollateralId");

                    b.HasIndex("CollateralId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanCollaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LoanStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculationType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCalculated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoanStatuses");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LtvSpreadTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxLtv")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Spread")
                        .HasColumnType("TEXT");

                    b.Property<int>("TariffSettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TariffSettingsId");

                    b.ToTable("LtvSpreadTiers");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Payment.LoanPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapitalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysLate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaymentId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanPayments");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.PaymentPlan", b =>
                {
                    b.Property<int>("PaymentPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAdvancedAnalytics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowApiAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowCustomBranding")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowExport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowImport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowMonteCarloSimulation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowMultipleFunds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowPortfolioAnalysis")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowReporting")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDebtors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxFunds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLoans")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StorageLimitMB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentPlanId");

                    b.ToTable("PaymentPlans");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.PlanAddOn", b =>
                {
                    b.Property<int>("AddOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AddOnId");

                    b.ToTable("PlanAddOns");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Ratios.CreditRatingThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RatioName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CreditRatingThresholds");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCollateralCorrelation")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCollateralExpectedReturn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCollateralVolatility")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCorporateTaxRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultEbitdaMarginVolatility")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultOperatingCostGrowthRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultOperatingCostVolatility")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultRevenueGrowthRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultRevenueVolatility")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityAgriculture")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityConstruction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityFinancialServices")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityHealthcare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityHospitality")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityManufacturing")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityOther")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityProfessionalServices")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityRealEstate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityRetail")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityTechnology")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SectorVolatilityTransportation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.PropertyTypeParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CorrelationWithRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedReturn")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volatility")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelSettingsId");

                    b.ToTable("PropertyTypeParameters");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorCollateralCorrelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CorrelationCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelSettingsId");

                    b.ToTable("SectorCollateralCorrelations");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorCorrelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CorrelationCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sector1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelSettingsId");

                    b.ToTable("SectorCorrelations");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultVolatility")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExpectedGrowth")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelSettingsId");

                    b.ToTable("SectorDefinitions");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.StandardRevenueCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StandardRevenueCategories");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TariffSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TariffSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TenantAddOn", b =>
                {
                    b.Property<int>("TenantAddOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddOnId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CustomAnnualPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CustomMonthlyPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnabledAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TenantAddOnId");

                    b.HasIndex("AddOnId");

                    b.HasIndex("TenantId", "AddOnId")
                        .IsUnique();

                    b.ToTable("TenantAddOns");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TenantCustomPricing", b =>
                {
                    b.Property<int>("CustomPricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BaseAnnualPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BaseMonthlyPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomMaxDebtors")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomMaxFunds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomMaxLoans")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomMaxUsers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomStorageLimitMB")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MultiYearDiscount")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricePerUser")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomPricingId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantCustomPricings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TenantPricingSummary", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveUserCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AgreedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgreedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgreedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualAddOnCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualUserCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyAddOnCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyUserCost")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TenantAgreed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAnnual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalMonthly")
                        .HasColumnType("TEXT");

                    b.HasKey("SummaryId");

                    b.HasIndex("AgreedById");

                    b.HasIndex("TenantId", "CalculatedAt");

                    b.ToTable("TenantPricingSummaries");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TenantSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("CustomAllowAdvancedAnalytics")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CustomAllowApiAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CustomAllowMonteCarloSimulation")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CustomAllowPortfolioAnalysis")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CustomAllowReporting")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomMaxDebtors")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomMaxFunds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomMaxLoans")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomMaxUsers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomStorageLimitMB")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PaymentPlanId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSubscriptions");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UsageTracking", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveUserCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiCallsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollateralCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DebtorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExportsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoanCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonteCarloSimulationsRun")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportsGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StorageUsedMB")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalUserCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsageId");

                    b.HasIndex("TenantId", "Year", "Month");

                    b.ToTable("UsageTrackings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UserAddOn", b =>
                {
                    b.Property<int>("UserAddOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddOnId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserAddOnId");

                    b.HasIndex("AddOnId");

                    b.HasIndex("AssignedById");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId", "AddOnId", "TenantId");

                    b.ToTable("UserAddOns");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UserFundAccess", b =>
                {
                    b.Property<int>("UserFundAccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserFundAccessId");

                    b.HasIndex("FundId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFundAccesses");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferenceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferenceValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PreferenceKey")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UserPricingTier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseAnnualPricePerUser")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseMonthlyPricePerUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinUsers")
                        .HasColumnType("INTEGER");

                    b.HasKey("TierId");

                    b.ToTable("UserPricingTiers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.AddOnPermission", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.PlanAddOn", "AddOn")
                        .WithMany("Permissions")
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.AddOnPricingTier", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.PlanAddOn", "AddOn")
                        .WithMany("PricingTiers")
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.ApplicationUser", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.BalanceSheetLineItem", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", "DebtorBalanceSheet")
                        .WithMany("LineItems")
                        .HasForeignKey("BalanceSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Collateral", "Collateral")
                        .WithMany()
                        .HasForeignKey("CollateralId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Loan.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Collateral");

                    b.Navigation("DebtorBalanceSheet");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CreditRatingSpread", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.TariffSettings", "TariffSettings")
                        .WithMany("CreditRatings")
                        .HasForeignKey("TariffSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TariffSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("BalanceSheets")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("ProfitAndLossStatements")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorSignatory", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "Debtor")
                        .WithMany("Signatories")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debtor");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.RevenueDetail", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", "DebtorPL")
                        .WithMany("RevenueDetails")
                        .HasForeignKey("PLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorPL");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Fund", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Tenant", "Tenant")
                        .WithMany("Funds")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("Loans")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LoanCollateral", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Collateral", "Collateral")
                        .WithMany("LoanCollaterals")
                        .HasForeignKey("CollateralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Loan.Loan", "Loan")
                        .WithMany("LoanCollaterals")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collateral");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.LtvSpreadTier", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.TariffSettings", "TariffSettings")
                        .WithMany("LtvTiers")
                        .HasForeignKey("TariffSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TariffSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Payment.LoanPayment", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Loan.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.PropertyTypeParameters", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", "ModelSettings")
                        .WithMany("PropertyTypeParameters")
                        .HasForeignKey("ModelSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorCollateralCorrelation", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", "ModelSettings")
                        .WithMany("SectorCollateralCorrelations")
                        .HasForeignKey("ModelSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorCorrelation", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", "ModelSettings")
                        .WithMany("SectorCorrelations")
                        .HasForeignKey("ModelSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.SectorDefinition", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", "ModelSettings")
                        .WithMany("SectorDefinitions")
                        .HasForeignKey("ModelSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelSettings");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TenantAddOn", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.PlanAddOn", "AddOn")
                        .WithMany("TenantAddOns")
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TenantCustomPricing", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Tenant", "Tenant")
                        .WithOne()
                        .HasForeignKey("LoanAnnuityCalculatorAPI.Models.TenantCustomPricing", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TenantPricingSummary", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", "AgreedBy")
                        .WithMany()
                        .HasForeignKey("AgreedById");

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgreedBy");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TenantSubscription", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.PaymentPlan", "PaymentPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PaymentPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Tenant", "Tenant")
                        .WithOne("Subscription")
                        .HasForeignKey("LoanAnnuityCalculatorAPI.Models.TenantSubscription", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentPlan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UsageTracking", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Tenant", "Tenant")
                        .WithMany("UsageHistory")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UserAddOn", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.PlanAddOn", "AddOn")
                        .WithMany("UserAddOns")
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById");

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", "User")
                        .WithMany("AddOns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("AssignedBy");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UserFundAccess", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Fund", "Fund")
                        .WithMany("UserAccesses")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", "User")
                        .WithMany("FundAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.UserPreference", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.ApplicationUser", b =>
                {
                    b.Navigation("AddOns");

                    b.Navigation("FundAccesses");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Collateral", b =>
                {
                    b.Navigation("LoanCollaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", b =>
                {
                    b.Navigation("BalanceSheets");

                    b.Navigation("Loans");

                    b.Navigation("ProfitAndLossStatements");

                    b.Navigation("Signatories");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.Navigation("RevenueDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Fund", b =>
                {
                    b.Navigation("UserAccesses");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.Navigation("LoanCollaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.PaymentPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.PlanAddOn", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("PricingTiers");

                    b.Navigation("TenantAddOns");

                    b.Navigation("UserAddOns");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Settings.ModelSettings", b =>
                {
                    b.Navigation("PropertyTypeParameters");

                    b.Navigation("SectorCollateralCorrelations");

                    b.Navigation("SectorCorrelations");

                    b.Navigation("SectorDefinitions");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.TariffSettings", b =>
                {
                    b.Navigation("CreditRatings");

                    b.Navigation("LtvTiers");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Tenant", b =>
                {
                    b.Navigation("Funds");

                    b.Navigation("Subscription");

                    b.Navigation("UsageHistory");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
