// <auto-generated />
using System;
using LoanAnnuityCalculatorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanAnnuityCalculatorAPI.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20251101151025_AddCollateralUniqueIdentifiers")]
    partial class AddCollateralUniqueIdentifiers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Collateral", b =>
                {
                    b.Property<int>("CollateralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppraisalDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AppraisalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssetUniqueId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LandRegistryCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SharedAssetGroup")
                        .HasColumnType("TEXT");

                    b.HasKey("CollateralId");

                    b.HasIndex("LoanId");

                    b.ToTable("Collaterals");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.CollateralIndex", b =>
                {
                    b.Property<int>("CollateralIndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceIndex")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CollateralIndexId");

                    b.ToTable("CollateralIndexes");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LongTermAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongTermLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OwnersEquity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorBalanceSheets");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", b =>
                {
                    b.Property<int>("DebtorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DebtorID");

                    b.ToTable("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostOfGoodsSold")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EBITDA")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InterestCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestExpense")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OperatingExpenses")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxExpense")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorPLs");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.RevenueDetail", b =>
                {
                    b.Property<int>("RevenueDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PLId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevenueCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RevenueDetailId");

                    b.HasIndex("PLId");

                    b.ToTable("RevenueDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.Property<int>("LoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestOnlyMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenorMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoanID");

                    b.HasIndex("DebtorID");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Ratios.CreditRatingThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RatioName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CreditRatingThresholds");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Collateral", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Loan.Loan", "Loan")
                        .WithMany("Collaterals")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("BalanceSheets")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("ProfitAndLossStatements")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.RevenueDetail", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", "DebtorPL")
                        .WithMany("RevenueDetails")
                        .HasForeignKey("PLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorPL");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("Loans")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", b =>
                {
                    b.Navigation("BalanceSheets");

                    b.Navigation("Loans");

                    b.Navigation("ProfitAndLossStatements");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.Navigation("RevenueDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.Navigation("Collaterals");
                });
#pragma warning restore 612, 618
        }
    }
}
