// <auto-generated />
using System;
using LoanAnnuityCalculatorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanAnnuityCalculatorAPI.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20251031112242_AddCascadeDeleteForDebtorRelations")]
    partial class AddCascadeDeleteForDebtorRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LongTermAssets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongTermLiabilities")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OwnersEquity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorBalanceSheets");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", b =>
                {
                    b.Property<int>("DebtorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DebtorID");

                    b.ToTable("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EBITDA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtorID");

                    b.ToTable("DebtorPLs");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.Property<int>("LoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestOnlyMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenorMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoanID");

                    b.HasIndex("DebtorID");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Ratios.CreditRatingThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RatioName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CreditRatingThresholds");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorBalanceSheet", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("BalanceSheets")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorPL", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("ProfitAndLossStatements")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Loan.Loan", b =>
                {
                    b.HasOne("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", "DebtorDetails")
                        .WithMany("Loans")
                        .HasForeignKey("DebtorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtorDetails");
                });

            modelBuilder.Entity("LoanAnnuityCalculatorAPI.Models.Debtor.DebtorDetails", b =>
                {
                    b.Navigation("BalanceSheets");

                    b.Navigation("Loans");

                    b.Navigation("ProfitAndLossStatements");
                });
#pragma warning restore 612, 618
        }
    }
}
