using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LoanAnnuityCalculatorAPI.Migrations
{
    /// <inheritdoc />
    public partial class SeedAdminUser : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Seed roles
            migrationBuilder.Sql(@"
                IF NOT EXISTS (SELECT * FROM AspNetRoles WHERE Name = 'Admin')
                BEGIN
                    INSERT INTO AspNetRoles (Id, Name, NormalizedName, ConcurrencyStamp)
                    VALUES (NEWID(), 'Admin', 'ADMIN', NEWID());
                END

                IF NOT EXISTS (SELECT * FROM AspNetRoles WHERE Name = 'RiskManager')
                BEGIN
                    INSERT INTO AspNetRoles (Id, Name, NormalizedName, ConcurrencyStamp)
                    VALUES (NEWID(), 'RiskManager', 'RISKMANAGER', NEWID());
                END

                IF NOT EXISTS (SELECT * FROM AspNetRoles WHERE Name = 'Viewer')
                BEGIN
                    INSERT INTO AspNetRoles (Id, Name, NormalizedName, ConcurrencyStamp)
                    VALUES (NEWID(), 'Viewer', 'VIEWER', NEWID());
                END
            ");

            // Seed admin user - NOTE: Password is Admin123!
            // This hash is generated by ASP.NET Core Identity PasswordHasher
            migrationBuilder.Sql(@"
                IF NOT EXISTS (SELECT * FROM AspNetUsers WHERE UserName = 'admin')
                BEGIN
                    DECLARE @UserId NVARCHAR(450) = CAST(NEWID() AS NVARCHAR(450));
                    DECLARE @AdminRoleId NVARCHAR(450);
                    
                    SELECT @AdminRoleId = Id FROM AspNetRoles WHERE Name = 'Admin';
                    
                    INSERT INTO AspNetUsers (
                        Id, UserName, NormalizedUserName, Email, NormalizedEmail, 
                        EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp, 
                        PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, AccessFailedCount,
                        FirstName, LastName, IsActive, CreatedAt, IsSystemAdmin
                    )
                    VALUES (
                        @UserId, 'admin', 'ADMIN', 'admin@loanannuity.local', 'ADMIN@LOANANNUITY.LOCAL',
                        1, 'AQAAAAIAAYagAAAAEJvmVxN7FkFz+JxH7Z8rJ5rKJ7h8GzPzXKzJ4nF3kF9zH8xG3cH2vP9qZzN5mY3rKw==',
                        CAST(NEWID() AS NVARCHAR(450)), CAST(NEWID() AS NVARCHAR(450)), 0, 0, 1, 0,
                        'Admin', 'User', 1, GETUTCDATE(), 1
                    );
                    
                    IF @AdminRoleId IS NOT NULL
                    BEGIN
                        INSERT INTO AspNetUserRoles (UserId, RoleId)
                        VALUES (@UserId, @AdminRoleId);
                    END
                END
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM AspNetUsers WHERE UserName = 'admin'");
            migrationBuilder.Sql("DELETE FROM AspNetRoles WHERE Name IN ('Admin', 'RiskManager', 'Viewer')");
        }
    }
}
