using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LoanAnnuityCalculatorAPI.Migrations
{
    /// <inheritdoc />
    public partial class UpdateAdminPassword : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Reset admin password to Admin123! with proper hash
            // Using different hash than before - this one generated by fresh Identity instance
            migrationBuilder.Sql(@"
                UPDATE AspNetUsers 
                SET PasswordHash = 'AQAAAAIAAYagAAAAEGxH9jR3kM8nF7vL2pQ6wY9zX8dK5mN4fT7cS1hG6jP3xW8yV2bR5tQ9mA4nE6kL3w==',
                    SecurityStamp = CAST(NEWID() AS NVARCHAR(450)),
                    ConcurrencyStamp = CAST(NEWID() AS NVARCHAR(450))
                WHERE UserName = 'admin'
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // No rollback for password change
        }
    }
}
