namespace LoanAnnuityCalculatorAPI.Models.DTOs
{
    public class BalanceSheetWithLineItemsDto
    {
        public int Id { get; set; }
        public int DebtorID { get; set; }
        public int BookYear { get; set; }
        public bool IsProForma { get; set; }
        
        // Summary totals
        public decimal CurrentAssets { get; set; }
        public decimal LongTermAssets { get; set; }
        public decimal CurrentLiabilities { get; set; }
        public decimal LongTermLiabilities { get; set; }
        public decimal OwnersEquity { get; set; }
        
        // Calculated totals
        public decimal TotalAssets => CurrentAssets + LongTermAssets;
        public decimal TotalLiabilities => CurrentLiabilities + LongTermLiabilities;
        
        // Detailed line items
        public List<BalanceSheetLineItemDto> LineItems { get; set; } = new List<BalanceSheetLineItemDto>();
    }

    public class BalanceSheetLineItemDto
    {
        public int Id { get; set; }
        public string Category { get; set; } = string.Empty;
        public string Label { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public int DisplayOrder { get; set; }
        public string? Notes { get; set; }
        public bool IsAutoGenerated { get; set; }
        
        // Foreign key IDs for creating new items
        public int? LoanId { get; set; }
        public int? CollateralId { get; set; }
        
        // Optional references (for display)
        public LoanReferenceDto? LoanReference { get; set; }
        public CollateralReferenceDto? CollateralReference { get; set; }
    }

    public class LoanReferenceDto
    {
        public int LoanId { get; set; }
        public decimal Rate { get; set; }
        public decimal OutstandingAmount { get; set; }
        public DateTime StartDate { get; set; }
        public int TenorMonths { get; set; }
        public string? Status { get; set; }
    }

    public class CollateralReferenceDto
    {
        public int CollateralId { get; set; }
        public string? PropertyType { get; set; }
        public string? Address { get; set; }
        public decimal? AppraisalValue { get; set; }
        public DateTime? AppraisalDate { get; set; }
        public string? CollateralType { get; set; }
    }
}
