using Microsoft.EntityFrameworkCore;
using LoanAnnuityCalculatorAPI.Data;
using LoanAnnuityCalculatorAPI.Models;

namespace LoanAnnuityCalculatorAPI.Services
{
    public class BalanceSheetMigrationService
    {
        private readonly LoanDbContext _context;
        private readonly ILogger<BalanceSheetMigrationService> _logger;
        private readonly LoanFinancialCalculatorService _loanCalculator;

        public BalanceSheetMigrationService(
            LoanDbContext context, 
            ILogger<BalanceSheetMigrationService> logger,
            LoanFinancialCalculatorService loanCalculator)
        {
            _context = context;
            _logger = logger;
            _loanCalculator = loanCalculator;
        }

        /// <summary>
        /// Migrates a balance sheet to use line items by creating line items from existing data
        /// </summary>
        public async Task<bool> MigrateBalanceSheet(int balanceSheetId, bool forceRefresh = false)
        {
            try
            {
                var balanceSheet = await _context.DebtorBalanceSheets
                    .Include(bs => bs.DebtorDetails)
                    .ThenInclude(d => d.Loans)
                    .ThenInclude(l => l.LoanCollaterals)
                    .ThenInclude(lc => lc.Collateral)
                    .FirstOrDefaultAsync(bs => bs.Id == balanceSheetId);

                if (balanceSheet == null)
                {
                    _logger.LogWarning($"Balance sheet {balanceSheetId} not found");
                    return false;
                }

                // Check if already migrated (skip check if forcing refresh)
                if (!forceRefresh)
                {
                    var existingLineItems = await _context.BalanceSheetLineItems
                        .Where(li => li.BalanceSheetId == balanceSheetId)
                        .CountAsync();

                    if (existingLineItems > 0)
                    {
                        _logger.LogInformation($"Balance sheet {balanceSheetId} already has {existingLineItems} line items");
                        return true;
                    }
                }

                _logger.LogInformation($"Migrating balance sheet {balanceSheetId} for debtor {balanceSheet.DebtorID}");

                var lineItems = new List<BalanceSheetLineItem>();
                int displayOrder = 1;

                // === ASSETS ===

                // 1. Current Assets from uploaded balance sheet (liquid assets)
                if (balanceSheet.CurrentAssets > 0)
                {
                    lineItems.Add(new BalanceSheetLineItem
                    {
                        BalanceSheetId = balanceSheet.Id,
                        Category = BalanceSheetCategory.CurrentAssets,
                        Label = "Current Assets",
                        Amount = balanceSheet.CurrentAssets,
                        DisplayOrder = displayOrder++,
                        IsAutoGenerated = true, // Mark as auto-generated so it gets refreshed
                        Notes = "Liquid assets from uploaded balance sheet (cash, receivables, inventory)"
                    });
                }

                // 2. Fixed Assets from collateral (auto-generated) - ONLY add these, don't add a separate Fixed Assets line
                // The uploaded balance sheet's LongTermAssets value is not reliable as it may or may not include collateral
                // We'll reconstruct fixed assets from collateral only
                var processedCollateralIds = new HashSet<int>();
                
                foreach (var loan in balanceSheet.DebtorDetails.Loans)
                {
                    foreach (var loanCollateral in loan.LoanCollaterals)
                    {
                        var collateral = loanCollateral.Collateral;
                        
                        // Skip if we've already added this collateral (multiple loans might share it)
                        if (processedCollateralIds.Contains(collateral.CollateralId))
                            continue;

                        processedCollateralIds.Add(collateral.CollateralId);

                        var label = !string.IsNullOrEmpty(collateral.PropertyAddress)
                            ? $"{collateral.PropertyType ?? "Property"} - {collateral.PropertyAddress}"
                            : $"{collateral.CollateralType} - {collateral.Description}";

                        lineItems.Add(new BalanceSheetLineItem
                        {
                            BalanceSheetId = balanceSheet.Id,
                            Category = BalanceSheetCategory.FixedAssets,
                            Label = label,
                            Amount = collateral.AppraisalValue ?? 0,
                            CollateralId = collateral.CollateralId,
                            DisplayOrder = displayOrder++,
                            IsAutoGenerated = true,
                            Notes = collateral.AppraisalDate.HasValue
                                ? $"Appraisal: €{collateral.AppraisalValue:N0} on {collateral.AppraisalDate.Value:yyyy-MM-dd}"
                                : $"Appraisal: €{collateral.AppraisalValue:N0}"
                        });
                    }
                }
                
                // NOTE: We do NOT add a separate "Fixed Assets" line item from balanceSheet.LongTermAssets
                // because that would double-count the collateral. The collateral line items above ARE the fixed assets.

                // === LIABILITIES ===

                // 4. Current Liabilities from uploaded balance sheet
                if (balanceSheet.CurrentLiabilities > 0)
                {
                    lineItems.Add(new BalanceSheetLineItem
                    {
                        BalanceSheetId = balanceSheet.Id,
                        Category = BalanceSheetCategory.CurrentLiabilities,
                        Label = "Current Liabilities",
                        Amount = balanceSheet.CurrentLiabilities,
                        DisplayOrder = displayOrder++,
                        IsAutoGenerated = true, // Mark as auto-generated so it gets refreshed
                        Notes = "Short-term liabilities from uploaded balance sheet (payables, short-term debt)"
                    });
                }

                // 5. Long-Term Liabilities from loans (auto-generated)
                foreach (var loan in balanceSheet.DebtorDetails.Loans)
                {
                    var label = $"Loan #{loan.LoanID}";
                    if (loan.AnnualInterestRate > 0)
                        label += $" @ {loan.AnnualInterestRate:F2}%";
                    
                    // Calculate outstanding balance as of the balance sheet date
                    var outstanding = _loanCalculator.CalculateOutstandingBalanceAtYear(loan, balanceSheet.BookYear);
                    var notes = $"Started: {loan.StartDate:yyyy-MM-dd}, Tenor: {loan.TenorMonths} months";
                    if (!string.IsNullOrEmpty(loan.Status))
                        notes += $", Status: {loan.Status}";

                    lineItems.Add(new BalanceSheetLineItem
                    {
                        BalanceSheetId = balanceSheet.Id,
                        Category = BalanceSheetCategory.LongTermLiabilities,
                        Label = label,
                        Amount = outstanding,
                        LoanId = loan.LoanID,
                        DisplayOrder = displayOrder++,
                        IsAutoGenerated = true,
                        Notes = notes
                    });
                }

                // 5b. First Lien Mortgage (External Loan) - auto-generated
                if (balanceSheet.FirstLienLoanAmount.HasValue && balanceSheet.FirstLienLoanAmount.Value > 0)
                {
                    var label = "External Loan (1st Lien Mortgage)";
                    if (balanceSheet.FirstLienInterestRate.HasValue && balanceSheet.FirstLienInterestRate.Value > 0)
                        label += $" @ {balanceSheet.FirstLienInterestRate.Value:F2}%";
                    
                    var notes = $"Amount: €{balanceSheet.FirstLienLoanAmount.Value:N0}";
                    if (balanceSheet.FirstLienTenorMonths.HasValue && balanceSheet.FirstLienTenorMonths.Value > 0)
                        notes += $", Tenor: {balanceSheet.FirstLienTenorMonths.Value} months";
                    if (!string.IsNullOrEmpty(balanceSheet.FirstLienRedemptionSchedule))
                        notes += $", Schedule: {balanceSheet.FirstLienRedemptionSchedule}";
                    notes += " - Senior debt with first lien on collateral";

                    lineItems.Add(new BalanceSheetLineItem
                    {
                        BalanceSheetId = balanceSheet.Id,
                        Category = BalanceSheetCategory.LongTermLiabilities,
                        Label = label,
                        Amount = balanceSheet.FirstLienLoanAmount.Value,
                        DisplayOrder = displayOrder++,
                        IsAutoGenerated = true,
                        Notes = notes
                    });
                }

                // 6. Other Long-Term Liabilities (calculated from uploaded balance sheet)
                // NOTE: Only add this during INITIAL migration, not during refresh
                // During refresh, we can't reliably calculate "other" liabilities because the original
                // balance sheet values included loan amounts that have changed
                if (!forceRefresh)
                {
                    decimal totalAutoGeneratedLTL = lineItems
                        .Where(li => li.Category == BalanceSheetCategory.LongTermLiabilities && li.IsAutoGenerated)
                        .Sum(li => li.Amount);

                    decimal manualLTL = balanceSheet.LongTermLiabilities - totalAutoGeneratedLTL;
                    if (manualLTL > 0.01m) // Use small threshold to avoid floating point issues
                    {
                        lineItems.Add(new BalanceSheetLineItem
                        {
                            BalanceSheetId = balanceSheet.Id,
                            Category = BalanceSheetCategory.LongTermLiabilities,
                            Label = "Other Long-Term Liabilities",
                            Amount = manualLTL,
                            DisplayOrder = displayOrder++,
                            IsAutoGenerated = true, // Mark as auto so it gets refreshed
                            Notes = "Long-term liabilities from uploaded balance sheet (excluding tracked loans)"
                        });
                    }
                }

                // Save all line items
                _context.BalanceSheetLineItems.AddRange(lineItems);
                await _context.SaveChangesAsync();

                _logger.LogInformation($"Created {lineItems.Count} line items for balance sheet {balanceSheetId}");

                // Recalculate and verify totals
                await RecalculateTotals(balanceSheet.Id);

                return true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Error migrating balance sheet {balanceSheetId}");
                return false;
            }
        }

        /// <summary>
        /// Migrates all balance sheets for a specific debtor
        /// </summary>
        public async Task<int> MigrateDebtorBalanceSheets(int debtorId)
        {
            var balanceSheetIds = await _context.DebtorBalanceSheets
                .Where(bs => bs.DebtorID == debtorId)
                .Select(bs => bs.Id)
                .ToListAsync();

            int successCount = 0;
            foreach (var id in balanceSheetIds)
            {
                if (await MigrateBalanceSheet(id))
                    successCount++;
            }

            _logger.LogInformation($"Migrated {successCount} of {balanceSheetIds.Count} balance sheets for debtor {debtorId}");
            return successCount;
        }

        /// <summary>
        /// Migrates all balance sheets in the database
        /// </summary>
        public async Task<int> MigrateAllBalanceSheets()
        {
            var balanceSheetIds = await _context.DebtorBalanceSheets
                .Select(bs => bs.Id)
                .ToListAsync();

            int successCount = 0;
            foreach (var id in balanceSheetIds)
            {
                if (await MigrateBalanceSheet(id))
                    successCount++;
            }

            _logger.LogInformation($"Migrated {successCount} of {balanceSheetIds.Count} balance sheets total");
            return successCount;
        }

        /// <summary>
        /// Recalculates balance sheet totals from line items
        /// </summary>
        public async Task RecalculateTotals(int balanceSheetId)
        {
            var balanceSheet = await _context.DebtorBalanceSheets
                .Include(bs => bs.LineItems)
                .FirstOrDefaultAsync(bs => bs.Id == balanceSheetId);

            if (balanceSheet == null) return;

            var oldValues = new
            {
                CurrentAssets = balanceSheet.CurrentAssets,
                LongTermAssets = balanceSheet.LongTermAssets,
                CurrentLiabilities = balanceSheet.CurrentLiabilities,
                LongTermLiabilities = balanceSheet.LongTermLiabilities,
                OwnersEquity = balanceSheet.OwnersEquity
            };

            balanceSheet.CurrentAssets = balanceSheet.LineItems
                .Where(li => li.Category == BalanceSheetCategory.CurrentAssets)
                .Sum(li => li.Amount);

            balanceSheet.LongTermAssets = balanceSheet.LineItems
                .Where(li => li.Category == BalanceSheetCategory.FixedAssets)
                .Sum(li => li.Amount);

            balanceSheet.CurrentLiabilities = balanceSheet.LineItems
                .Where(li => li.Category == BalanceSheetCategory.CurrentLiabilities)
                .Sum(li => li.Amount);

            balanceSheet.LongTermLiabilities = balanceSheet.LineItems
                .Where(li => li.Category == BalanceSheetCategory.LongTermLiabilities)
                .Sum(li => li.Amount);

            decimal totalAssets = balanceSheet.CurrentAssets + balanceSheet.LongTermAssets;
            decimal totalLiabilities = balanceSheet.CurrentLiabilities + balanceSheet.LongTermLiabilities;
            balanceSheet.OwnersEquity = totalAssets - totalLiabilities;

            await _context.SaveChangesAsync();

            _logger.LogInformation($"Recalculated totals for balance sheet {balanceSheetId}:");
            _logger.LogInformation($"  Current Assets: {oldValues.CurrentAssets:N0} -> {balanceSheet.CurrentAssets:N0}");
            _logger.LogInformation($"  Fixed Assets: {oldValues.LongTermAssets:N0} -> {balanceSheet.LongTermAssets:N0}");
            _logger.LogInformation($"  Current Liabilities: {oldValues.CurrentLiabilities:N0} -> {balanceSheet.CurrentLiabilities:N0}");
            _logger.LogInformation($"  Long-Term Liabilities: {oldValues.LongTermLiabilities:N0} -> {balanceSheet.LongTermLiabilities:N0}");
            _logger.LogInformation($"  Owners Equity: {oldValues.OwnersEquity:N0} -> {balanceSheet.OwnersEquity:N0}");
        }

        /// <summary>
        /// Refreshes auto-generated line items (from loans and collateral) for a balance sheet
        /// </summary>
        public async Task RefreshAutoGeneratedLineItems(int balanceSheetId)
        {
            // Remove existing auto-generated line items
            var autoGenerated = await _context.BalanceSheetLineItems
                .Where(li => li.BalanceSheetId == balanceSheetId && li.IsAutoGenerated)
                .ToListAsync();

            _context.BalanceSheetLineItems.RemoveRange(autoGenerated);
            await _context.SaveChangesAsync();

            _logger.LogInformation($"Removed {autoGenerated.Count} auto-generated line items from balance sheet {balanceSheetId}");

            // Re-migrate to create fresh auto-generated items (force refresh to skip existing items check)
            await MigrateBalanceSheet(balanceSheetId, forceRefresh: true);
        }
    }
}
